plugins:
  discourse_mealie_enabled:
    default: false

  mealie_url:
    default: ""
    type: string
    description: "The base URL of your Mealie instance"

  mealie_api_key:
    default: ""
    type: string
    description: "Your Mealie API key for authentication"
    
  test_mealie_connection:
    type: button
    label: "Test Connection"
    description: "Click to test connection to the Mealie API."
    action: "mealie.test_connection"