mealie_url:
  default: ""
  description: "The base URL of your Mealie instance (e.g., https://mealie.example.com)"

mealie_api_key:
  default: ""
  type: secret
  description: "API Key for accessing Mealie's API"
