plugins:
  Discourse_Mealie:
    mealie_url:
      default: ""
      type: string
      description: "The base URL of your Mealie instance"

    mealie_api_key:
      default: ""
      type: string
      description: "Your Mealie API key for authentication"
