# config/settings.yml
plugins:
  mealie_integration_enabled:
    default: false
    client: true
  mealie_url:
    default: ""
    client: false
  mealie_api_key:
    default: ""
    client: false
    secret: true
  mealie_default_category_id:
    default: 0
    client: false
  mealie_tag:
    default: "recipe"
    client: false
  mealie_sync_frequency:
    default: 0
    client: false
    enum: "SiteSetting.mealie_sync_frequency"
  mealie_last_sync:
    default: ""
    client: false
    hidden: true